name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Pages
      uses: actions/configure-pages@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src  # The directory where your HTML files are located (root folder in this case)
        target_branch: gh-pages  # The branch to deploy to (commonly "gh-pages")
